# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/wf_ksrm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wf_ksrm(object):
    def setupUi(self, wf_ksrm):
        wf_ksrm.setObjectName("wf_ksrm")
        wf_ksrm.resize(738, 398)
        wf_ksrm.setMinimumSize(QtCore.QSize(0, 0))
        wf_ksrm.setStyleSheet("QLabel{\n"
"border-radius: 10px; \n"
"    \n"
"    background-color: rgba(0, 0, 0, 200);\n"
"}\n"
"QPushButton{\n"
"    border-radius: 12px; \n"
"    \n"
"    background-color: rgba(0, 0, 0, 200);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgba(255, 255, 127,200);\n"
"}\n"
"QPushButton:pressed{\n"
"    \n"
"    \n"
"    background-color: rgba(0, 0, 255, 200);\n"
"}\n"
"\n"
"#bt_gb{\n"
"    color: rgb(255, 0, 0);\n"
"    \n"
"    font: 75 14pt \"微软雅黑\";\n"
"}\n"
"#bt_zxh{\n"
"    color: rgb(0, 170, 0);\n"
"    \n"
"    font: 75 14pt \"微软雅黑\";\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(wf_ksrm)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_doc = QtWidgets.QLabel(wf_ksrm)
        self.lb_doc.setMinimumSize(QtCore.QSize(700, 0))
        self.lb_doc.setWordWrap(True)
        self.lb_doc.setObjectName("lb_doc")
        self.horizontalLayout.addWidget(self.lb_doc)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bt_gb = QtWidgets.QPushButton(wf_ksrm)
        self.bt_gb.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.bt_gb.setFont(font)
        self.bt_gb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_gb.setObjectName("bt_gb")
        self.verticalLayout.addWidget(self.bt_gb)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.bt_zxh = QtWidgets.QPushButton(wf_ksrm)
        self.bt_zxh.setMinimumSize(QtCore.QSize(28, 28))
        self.bt_zxh.setMaximumSize(QtCore.QSize(28, 28))
        self.bt_zxh.setSizeIncrement(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.bt_zxh.setFont(font)
        self.bt_zxh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_zxh.setObjectName("bt_zxh")
        self.verticalLayout.addWidget(self.bt_zxh)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(wf_ksrm)
        self.bt_gb.clicked.connect(wf_ksrm.close)
        self.bt_zxh.clicked.connect(wf_ksrm.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(wf_ksrm)

    def retranslateUi(self, wf_ksrm):
        _translate = QtCore.QCoreApplication.translate
        wf_ksrm.setWindowTitle(_translate("wf_ksrm", "Form"))
        self.lb_doc.setText(_translate("wf_ksrm", "<html><head/><body><p><a href=\"https://www.bilibili.com/video/av27789609\"><span style=\" font-size:18pt; font-weight:600; text-decoration: underline; color:#ffff00;\">小甲鱼python基础视频教程</span></a></p><p><a href=\"https://www.bilibili.com/video/BV1wD4y1o7AS\"><span style=\" font-size:18pt; font-weight:600; text-decoration: underline; color:#ffff00;\">马士兵python</span></a><a href=\"https://www.bilibili.com/video/av27789609\"><span style=\" font-size:18pt; font-weight:600; text-decoration: underline; color:#ffff00;\">基础</span></a><a href=\"https://www.bilibili.com/video/BV1wD4y1o7AS\"><span style=\" font-size:18pt; font-weight:600; text-decoration: underline; color:#ffff00;\">视频教程</span></a></p><p><a href=\"https://www.liaoxuefeng.com/wiki/1016959663602400\"><span style=\" font-size:18pt; font-weight:600; text-decoration: underline; color:#ffff00;\">廖雪峰pyhhon基础文字教程</span></a></p><p><br/><span style=\" font-size:18pt; font-weight:600; color:#ff0000;\">学习技巧:(有事没事就百度,然后建立自己的字典)</span></p><p><span style=\" font-size:11pt; color:#ffffff;\">以上教程选择性的观看觉得哪个适合你就看哪个,正常人只需要看过一遍,然后自己跟着写一遍即可,没记住关键字和单词无所谓,只需要记住常用的比如print for if try这些其它的只需要有印象,记住首字母然后用有道笔记把单词填进去,每天过一遍就好. 切记把自己跟着写的代码都存好,备注写的越详细越好,方便以后忘记了翻看,有了这些加上你脑子里的印象,然后就开始写一个自己擅长,符合自己兴趣的项目,比如喜欢游戏就可以尝试写一个辅助工具,喜欢音乐,可以写一个听歌软件(有人会说,我好像没学过这些,搞不定吧.实际上你已经学了,有了上面的学习你已经有能力遇到问题就去百度了,百度之后你也大部分能够慢慢理解了.)</span></p><p><span style=\" font-size:16pt; font-weight:600; color:#aa007f;\">为了保护版权,我就不直接爬取内容了,直接跳转网页方便点.</span></p></body></html>"))
        self.bt_gb.setText(_translate("wf_ksrm", "X"))
        self.bt_zxh.setText(_translate("wf_ksrm", "━"))
